### ISSUE TITLE
I can't add a item to list in config file

### ISSUE THREAD

**Issue by AlexMartSch** [DomeDD/DeveloperAPI#1]
As the title says, I simply can not add anything to the list, no errors appear in the console.
My code is as follows:

`	FileBuilder fb = new FileBuilder("plugins/MyPlugin/ServerData", "staffList.yml");`

`fb.getStringList("Staff.StaffList").add(X+args[1]);
fb.save();
fb.reload();`

Note; args[1] its for a command.
Please.

**Comment by DomeDD** [comment]
`FileBuilder fb = new FileBuilder("plugins/MyPlugin/ServerData", "staffList.yml");`
`List<String> list = fb.getStringList("Staff.StaffList");`
`list.add(X+args[0]);`
`fb.set("Staff.StaffList", list);`
`fb.save();`
`fb.reload()`
